DELETE FROM FILE;
DELETE FROM TAG;
DELETE FROM FILE_TAG;

INSERT INTO FILE VALUES ('foo.py', 1234);
INSERT INTO FILE VALUES ('bar.py', 1235);
INSERT INTO FILE VALUES ('baz.py', 1236);

INSERT INTO TAG VALUES ('tag1');
INSERT INTO TAG VALUES ('tag2');
INSERT INTO TAG VALUES ('tag3');

INSERT INTO FILE_TAG VALUES ('foo.py', 'tag1');
INSERT INTO FILE_TAG VALUES ('foo.py', 'tag2');
INSERT INTO FILE_TAG VALUES ('bar.py', 'tag1');

